---
title: "table1_sl_outcomes"
author: "Drew Walker"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(table1)
library(haven)
```

```{r read-data}
sl_demo_raw <- read_csv("table1.csv")

str(sl_demo_raw)

sl_demo_raw$streetlight_evaluation_survey_complete <- as.factor(sl_demo_raw$streetlight_evaluation_survey_complete)
sl_demo_raw$yqolsf_complete <- as.factor(sl_demo_raw$yqolsf_complete)

sl_demo_raw$demographic_questionnaire_complete <- as.factor(sl_demo_raw$demographic_questionnaire_complete)

sl_demo_raw$gender <- as.factor(sl_demo_raw$gender)

sl_demo_raw$diagnosis <- as.factor(sl_demo_raw$diagnosis)

sl_demo_raw$ethnicity <- as.factor(sl_demo_raw$ethnicity)

sl_demo_raw$other_disease <- as.factor(sl_demo_raw$other_disease)

sl_demo_clean <- sl_demo_raw %>% 
  mutate(interview_requested = case_when(is.na(interview_request_name) ~ "No",
                                         TRUE ~ "Yes"),
         sl_outcomes_avg = (q1_control+q2_getalong_hosp+q3_getalong_fam+q4_easier_tasks+q6_roomhang_fun+q7_friends_roomhang+q8_talk_badday+q_32+q11_respect_all+q13_badday_there+q14_there_hang+q15_sl_friends+q16_hang_better+q17_eot_good+q18_imp_treat_event+q19_happy_mem)/16,
         sl_outcomes_sum = (q1_control+q2_getalong_hosp+q3_getalong_fam+q4_easier_tasks+q6_roomhang_fun+q7_friends_roomhang+q8_talk_badday+q_32+q11_respect_all+q13_badday_there+q14_there_hang+q15_sl_friends+q16_hang_better+q17_eot_good+q18_imp_treat_event+q19_happy_mem),
         sl_friends = (q8_talk_badday+q_32+q15_sl_friends+q7_friends_roomhang+q18_imp_treat_event+q14_there_hang+q13_badday_there)/7,
         sl_friends_sum = (q8_talk_badday+q_32+q15_sl_friends+q7_friends_roomhang+q18_imp_treat_event+q14_there_hang+q13_badday_there),
         sl_family = (q2_getalong_hosp+q4_easier_tasks+q3_getalong_fam+q1_control+q17_eot_good)/5,
         sl_family_sum = (q2_getalong_hosp+q4_easier_tasks+q3_getalong_fam+q1_control+q17_eot_good),
         sl_diversion = (q19_happy_mem+q11_respect_all+q6_roomhang_fun+q16_hang_better)/4,
         sl_diversion_sum = (q19_happy_mem+q11_respect_all+q6_roomhang_fun+q16_hang_better),
         yqol_friends = (r27+r24+r07+r26+r08)/5,
         yqol_friends_sum = (r27+r24+r07+r26+r08),
         yqol_family = (r19+r16+r20+r36)/4,
         yqol_family_sum = (r19+r16+r20+r36),
         yqol_meaning = (r32+r11)/2,
         yqol_meaning_sum = (r32+r11),
         yqol_outcomes_avg = (r07+r08+r11+r16+r19+r20+r24+r26+r27+r32+r36)/11,
         yqol_outcomes_sum = (r07+r08+r11+r16+r19+r20+r24+r26+r27+r32+r36))
           

# ones not applicable to all
#q24_slmemb_ill, q25_outpat_trans_talk, q26_outpattrans_friend, q27_adulttrans_talk, q28_adulttrans_friend, q30_cf_yearbook, q31_experience
           
#q21_lounge_fun,q23_lounge_age 
sl_demo_clean$interview_requested <- as.factor(sl_demo_clean$interview_requested)

sl_demo_clean$school___1 <- as.factor(sl_demo_clean$school___1)
sl_demo_clean$school___2 <- as.factor(sl_demo_clean$school___2)
sl_demo_clean$school___3 <- as.factor(sl_demo_clean$school___3)
sl_demo_clean$school___4 <- as.factor(sl_demo_clean$school___4)
sl_demo_clean$school___5 <- as.factor(sl_demo_clean$school___5)
sl_demo_clean$school___6 <- as.factor(sl_demo_clean$school___6)
sl_demo_clean$school___7 <- as.factor(sl_demo_clean$school___7)
sl_demo_clean$school___8 <- as.factor(sl_demo_clean$school___8)
sl_demo_clean$school___9 <- as.factor(sl_demo_clean$school___9)
sl_demo_clean$hospital_now <- as.factor(sl_demo_clean$hospital_now)


table1(~streetlight_evaluation_survey_complete + yqolsf_complete + demographic_questionnaire_complete + gender + diagnosis + ethnicity + other_disease + interview_requested + age + yqol_outcomes_avg +sl_outcomes_avg + school___1 +school___2+ school___3+ school___4+school___5+ school___6+ school___7+ school___8+ school___9 + hospital_now, data = sl_demo_clean )
```
# Sensitivity/logistic regressions for qual of life and SL eval outcome scores
* if ppl selected to interview-- no significant relationship
* if ppl were in hospital -- no sig relationship 
* differences across disease populations  -- no sig relationship
* association between scores  --

```{r regressions}
sl_demo_clean$hospital_now
model_interview_yqol <- lm(yqol_outcomes_avg~interview_requested, data = sl_demo_clean)
summary(model_interview_yqol)

model_interview_sl <- lm(sl_outcomes_avg~interview_requested, data= sl_demo_clean)
summary(model_interview_sl)

# No significant associations between requested interview and YQOL/SL 

model_hospital_yqol <- lm(yqol_outcomes_avg~hospital_now, data = sl_demo_clean)
summary(model_hospital_yqol)

model_hospital_sl <- lm(sl_outcomes_avg~hospital_now, data= sl_demo_clean)
summary(model_hospital_sl)

# No significant associaitons here whether hospitalized/not- may point to need to continue services outpatient related to QOL 

model_diagnosis_yqol <- lm(yqol_outcomes_avg~diagnosis, data = sl_demo_clean)
summary(model_diagnosis_yqol)

model_diagnosis_sl <- lm(sl_outcomes_avg~diagnosis, data= sl_demo_clean)
summary(model_diagnosis_sl)

# No significant associations here

model_sl_and_yqol <- lm(yqol_outcomes_avg ~ sl_outcomes_avg, data = sl_demo_clean)
summary(model_sl_and_yqol)

# none found here

## Add age 
model_age_yqol <- lm(yqol_outcomes_avg~age, data = sl_demo_clean)
summary(model_age_yqol)

model_age_sl <- lm(sl_outcomes_avg~age, data= sl_demo_clean)
summary(model_age_sl)

# and gender 

model_gender_yqol <- lm(yqol_outcomes_avg~gender, data = sl_demo_clean)
summary(model_gender_yqol)

model_gender_sl <- lm(sl_outcomes_avg~gender, data= sl_demo_clean)
summary(model_gender_sl)

```
# Factor models

* Using EFA factors as regression predictors/outcomes 

```{r }

#yqol_friends, yqol_family ,yqol_meaning 
model_friends_factor <- lm(yqol_friends~sl_outcomes_avg, data= sl_demo_clean)
summary(model_friends_factor)

model_family_factor <- lm(yqol_family~sl_outcomes_avg, data= sl_demo_clean)
summary(model_family_factor)

model_meaning_factor <- lm(yqol_meaning~sl_outcomes_avg, data= sl_demo_clean)
summary(model_meaning_factor)


## Specific SL Factors sl_friends, sl_family, sl_diversion

model_friends_sl_factors <- lm(yqol_friends~sl_friends + sl_family + sl_diversion, data= sl_demo_clean)
summary(model_friends_sl_factors)

model_family_sl_factors <- lm(yqol_family~sl_friends + sl_family + sl_diversion , data= sl_demo_clean)
summary(model_family_sl_factors)

model_meaning_sl_factors <- lm(yqol_meaning~sl_friends + sl_family + sl_diversion, data= sl_demo_clean)
summary(model_meaning_sl_factors)


## Redoing with sums as sensitivity check 

#yqol_friends, yqol_family ,yqol_meaning 
model_friends_factor_sum <- lm(yqol_friends_sum~sl_outcomes_sum, data= sl_demo_clean)
summary(model_friends_factor_sum)

model_family_factor_sum <- lm(yqol_family_sum~sl_outcomes_sum, data= sl_demo_clean)
summary(model_family_factor_sum)

model_meaning_factor_sum <- lm(yqol_meaning_sum~sl_outcomes_sum, data= sl_demo_clean)
summary(model_meaning_factor_sum)


## Specific SL Factors sl_friends, sl_family, sl_diversion

model_friends_sl_factors_sum <- lm(yqol_friends_sum~sl_friends_sum + sl_family_sum + sl_diversion_sum, data= sl_demo_clean)
summary(model_friends_sl_factors_sum)

model_family_sl_factors_sum <- lm(yqol_family_sum~sl_friends_sum + sl_family_sum + sl_diversion_sum , data= sl_demo_clean)
summary(model_family_sl_factors_sum)

model_meaning_sl_factors_sum <- lm(yqol_meaning_sum~sl_friends_sum + sl_family_sum + sl_diversion_sum, data= sl_demo_clean)
summary(model_meaning_sl_factors_sum)
```

